#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh
xsetroot -cursor_name left_ptr &

bspc monitor -d 1 2 3 4 5

bspc config border_width         0
bspc config window_gap           15

# Coloring

bspc config focused_border_color	\#555555
bspc config urgent_border_color 	\#ff0000
bspc config single_monocle true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a Thunar state=floating
bspc rule -a spotify desktop='^9' state=floating
bspc rule -a kitty state=pseudo_tiled
bspc rule -a Viewnior state=floating
bspc rule -a Zathura state=floating


#keymap for spanish keyboard distribution
setxkbmap latam
